version: '3.3'
services:
    mariadb:
        image: mariadb
        restart: always
        container_name: mariadb
        ports:
        - 3308:3306
        environment:
            MYSQL_DATABASE: seajobs
            MYSQL_ROOT_PASSWORD: QKh8RrWnc51CNcs2DigDsTIxg9J1SXZo
            MYSQL_USER: username
            MYSQL_PASSWORD: QKh8RrWnc51CNcs2DigDsTIxg9J1SXZo
        volumes:
            - ./Mariadb:/docker-entrypoint-initdb.d
            - ./DB:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
        - 8085:8080
