version: '3.3'
services:
    mariadb:
        image: mariadb
        restart: always
        container_name: mariadb
        ports:
        - 3306:3306
        environment:
            MYSQL_DATABASE: seajobs
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_USER: username
            MYSQL_PASSWORD: mypass
        volumes:
            - ./Mariadb:/docker-entrypoint-initdb.d
            - ./DB:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
        - 8085:8080
