"""
Django settings for seajobs_server project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(#pz(#^q1g0corepo#(5$ov+u6pi_)et=v3%ugu_z3125%!x!5'

# SECURITY WARNING: don't run with debug turned on in production!
#TODO: change to False on deploy
DEBUG = True

ALLOWED_HOSTS = ['crewmarine.eu', 'crewmarine.ru', '*']


# Application definition

CORS_ORIGIN_ALLOW_ALL=True
CORS_ORIGIN_WHITELIST = [
    'http://google.com',
    'http://hostname.example.com',
    'http://localhost:8000',
    'http://127.0.0.1:9000',
    'http://crewmarine.eu',
    'https://crewmarine.eu',
]


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'seajobs_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'seajobs_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
if DEBUG:
    MEDIA_ROOT = '/tmp/'
    CV_ROOT = MEDIA_ROOT + MEDIA_URL + "/cv/"
    LOGO_ROOT = MEDIA_ROOT + MEDIA_URL + "/logo/"
else:
    MEDIA_ROOT = '/var/www/u1172916/data/'
    CV_ROOT = MEDIA_ROOT + MEDIA_URL
    LOGO_ROOT = MEDIA_ROOT + MEDIA_URL

DB_NAME = "u1172916_default"
# DB_NAME = "seajobs"
DB_USER = "u1172916_default"
# DB_USER = "username"
DB_PASSWORD = "Ml7i_S4q"
# DB_PASSWORD = "QKh8RrWnc51CNcs2DigDsTIxg9J1SXZo"
# For docker startup:

if DEBUG:
    DB_HOST = "mariadb"
else:
    DB_HOST = "localhost"
DB_PORT = 3306
# For debug:
# DB_HOST = "128.0.129.115"
# DB_PORT = 3308
MAIL_ADDR = "seajobs.development@gmail.com"
MAIL_PASS = "Kpl5xKpdzPaHnQ1y"
MAIL_NAME = "Crewmarine"
PASSWORD_RESET_URL = "https://proger00.ddns.net/en/reset_password.html"
ENCODING = "utf-8"

MAX_VACATIONS_DISPLAYED = 100
MAX_REG_REQUESTS_DISPLAYED = 100

ADMIN_EMAIL = "admin@admin.admin"
